language: python
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
python:
  - "3.6"
install:
  - pip install peotry && poetry install
script:
  - poetry run py.test tests
after_success:
  - codecov
