language: python
dist: xenial
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
python:
  - "3.7"
install:
  - pip install poetry && poetry install
script:
  - poetry run pytest tests
after_success:
  - codecov
