language: python
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
python:
  - "3.6"
  - "3.7"
install:
  - pip install poetry && poetry install
script:
  - poetry run py.test tests
after_success:
  - codecov
