language: python
dist: xenial
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
python:
  - "3.7"
install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v
script:
  - poetry run pytest tests
after_success:
  - codecov
